name: Run Tests

on: [push, pull_request]

jobs:
  node_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20, 22]
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Create NYC folder
        run: mkdir .nyc_output
      - name: Install Dependencies
        run: npm install --legacy-peer-deps
      - name: Run tests
        run: npm run test
      - name: Run integration tests
        if: ${{ secrets.TEST_API_KEY != '' }}
        env:
          TEST_API_KEY: ${{ secrets.TEST_API_KEY }}
          LIVE_API_KEY: ${{ secrets.LIVE_API_KEY }}
        run: npm run test:integration
      - name: Run tests with CTRF reporter
        run: npx mocha test --reporter mocha-ctrf-json-reporter
        if: always()
      - name: Publish Test Results (CTRF)
        uses: ctrf-io/github-test-reporter@v1
        with:
          report-path: 'ctrf/*.json'
        if: always()
      - name: Coverage
        if: matrix.node == 20
        run: npm run test-lcov
      - name: Upload coverage to Codecov
        if: matrix.node == 20
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          flags: unit
          fail_ci_if_error: false
